package glass.relay.bridge.connector

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.json.JSONObject
import java.io.IOException
import java.net.HttpURLConnection
import java.net.URL
import java.security.MessageDigest
import javax.crypto.Mac
import javax.crypto.spec.SecretKeySpec

/**
 * The phone's half of the connector — see `connector/src/protocol.ts`, which is
 * the single source of truth for the wire format.
 *
 * Ported from `connector/src/client.ts` method for method, deliberately. Three
 * implementations have to agree byte for byte on the signature construction, so
 * `ConnectorSigningTest` pins this one against a vector generated by the
 * TypeScript implementation. If that test fails, the two have diverged and every
 * request from this platform will be rejected.
 *
 * Uses `HttpURLConnection` rather than OkHttp on purpose: this module has no
 * third-party dependencies, and the whole surface used here is four calls.
 */
class ConnectorClient(
    private val baseUrl: String,
    private var credentials: Credentials? = null,
    private val now: () -> Long = { System.currentTimeMillis() },
) {

    data class Credentials(val deviceToken: String, val signingKey: String)

    data class SessionManifest(
        val sessionId: String,
        val kind: String,
        val startedAtMs: Long,
        val durationS: Int,
        val totalBytes: Long,
        val chunkBytes: Int,
        val encoding: String,
        val sourceName: String,
    ) {
        fun toJson(): String = JSONObject()
            .put("sessionId", sessionId)
            .put("kind", kind)
            .put("startedAtMs", startedAtMs)
            .put("durationS", durationS)
            .put("totalBytes", totalBytes)
            .put("chunkBytes", chunkBytes)
            .put("encoding", encoding)
            .put("sourceName", sourceName)
            .toString()
    }

    data class SessionStatus(
        val sessionId: String,
        val receivedChunks: Set<Int>,
        val expectedChunks: Int,
        val complete: Boolean,
        val nextChunk: Int?,
    )

    data class UploadProgress(
        val sentChunks: Int,
        val totalChunks: Int,
        val sentBytes: Long,
        val totalBytes: Long,
        val skippedChunks: Int,
    )

    fun credentials(): Credentials? = credentials

    suspend fun pair(
        deviceId: String,
        deviceName: String,
        pairingCode: String,
    ): Credentials = withContext(Dispatchers.IO) {
        val body = JSONObject()
            .put("deviceId", deviceId)
            .put("platform", "android")
            .put("deviceName", deviceName)
            .put("pairingCode", pairingCode)
            .toString()
            .toByteArray()

        val connection = open("POST", "/v1/pair")
        connection.setRequestProperty("content-type", "application/json")
        connection.doOutput = true
        connection.outputStream.use { it.write(body) }

        val response = readResponse(connection)
        if (response.code != 200) throw IOException("pairing failed: ${response.code} ${response.text}")

        val json = JSONObject(response.text)
        Credentials(
            deviceToken = json.getString("deviceToken"),
            signingKey = json.getString("signingKey"),
        ).also { credentials = it }
    }

    suspend fun declare(manifest: SessionManifest): SessionStatus = withContext(Dispatchers.IO) {
        val response = send("POST", "/v1/sessions", manifest.toJson().toByteArray(), "application/json")
        if (response.code != 200) throw IOException("declare failed: ${response.code} ${response.text}")
        parseStatus(response.text)
    }

    suspend fun status(sessionId: String): SessionStatus = withContext(Dispatchers.IO) {
        val response = send("GET", "/v1/sessions/${encode(sessionId)}/status", ByteArray(0), null)
        if (response.code != 200) throw IOException("status failed: ${response.code} ${response.text}")
        parseStatus(response.text)
    }

    suspend fun complete(sessionId: String): SessionStatus = withContext(Dispatchers.IO) {
        val response = send("POST", "/v1/sessions/${encode(sessionId)}/complete", ByteArray(0), null)
        if (response.code != 200) throw IOException("complete failed: ${response.code} ${response.text}")
        parseStatus(response.text)
    }

    /**
     * Upload a session, sending only what the box does not already have.
     *
     * The resume query is unconditional. A phone that uploaded 39 of 40 chunks
     * before losing signal does not know that it did; asking costs one small
     * round trip and can save an hour of radio.
     */
    suspend fun upload(
        manifest: SessionManifest,
        data: ByteArray,
        onProgress: (UploadProgress) -> Unit = {},
    ): SessionStatus {
        val chunkBytes = manifest.chunkBytes
        val totalChunks = if (data.isEmpty()) 0 else (data.size + chunkBytes - 1) / chunkBytes

        declare(manifest)
        val already = status(manifest.sessionId).receivedChunks

        var sentChunks = 0
        var sentBytes = 0L

        for (index in 0 until totalChunks) {
            val start = index * chunkBytes
            val end = minOf(start + chunkBytes, data.size)
            val slice = data.copyOfRange(start, end)

            if (index in already) {
                sentBytes += slice.size
                continue
            }

            putChunk(manifest.sessionId, index, slice)
            sentChunks += 1
            sentBytes += slice.size
            onProgress(
                UploadProgress(
                    sentChunks = sentChunks,
                    totalChunks = totalChunks,
                    sentBytes = sentBytes,
                    totalBytes = data.size.toLong(),
                    skippedChunks = already.size,
                ),
            )
        }

        return complete(manifest.sessionId)
    }

    private suspend fun putChunk(
        sessionId: String,
        sequence: Int,
        body: ByteArray,
    ) = withContext(Dispatchers.IO) {
        val response = send(
            method = "POST",
            path = "/v1/sessions/${encode(sessionId)}/chunks",
            body = body,
            contentType = "application/octet-stream",
            extraHeaders = mapOf(HEADER_SEQUENCE to sequence.toString()),
        )
        // 208 means the box already held this chunk, which is success: a client
        // retrying after a lost ACK behaved correctly.
        if (response.code != 200 && response.code != 208) {
            throw IOException("chunk $sequence failed: ${response.code} ${response.text}")
        }
    }

    // --- plumbing ------------------------------------------------------------

    private class RawResponse(val code: Int, val text: String)

    private fun open(method: String, path: String): HttpURLConnection =
        (URL("$baseUrl$path").openConnection() as HttpURLConnection).apply {
            requestMethod = method
            connectTimeout = CONNECT_TIMEOUT_MS
            // Deliberately generous: a chunk over BLE-limited uplink on a train
            // is slow but succeeding, and aborting it wastes the whole transfer.
            readTimeout = READ_TIMEOUT_MS
        }

    private fun send(
        method: String,
        path: String,
        body: ByteArray,
        contentType: String?,
        extraHeaders: Map<String, String> = emptyMap(),
    ): RawResponse {
        val creds = credentials ?: throw IllegalStateException("not paired")

        val bodyHash = sha256Hex(body)
        val timestamp = now()
        val signature = sign(creds.signingKey, method, path, bodyHash, timestamp)

        val connection = open(method, path)
        connection.setRequestProperty(HEADER_TOKEN, "Bearer ${creds.deviceToken}")
        connection.setRequestProperty(HEADER_TIMESTAMP, timestamp.toString())
        connection.setRequestProperty(HEADER_SIGNATURE, signature)
        connection.setRequestProperty(HEADER_CONTENT_HASH, bodyHash)
        contentType?.let { connection.setRequestProperty("content-type", it) }
        extraHeaders.forEach { (key, value) -> connection.setRequestProperty(key, value) }

        if (method != "GET") {
            connection.doOutput = true
            connection.setFixedLengthStreamingMode(body.size)
            connection.outputStream.use { it.write(body) }
        }

        return readResponse(connection)
    }

    private fun readResponse(connection: HttpURLConnection): RawResponse {
        val code = connection.responseCode
        val stream = if (code in 200..299) connection.inputStream else connection.errorStream
        val text = stream?.bufferedReader()?.use { it.readText() } ?: ""
        connection.disconnect()
        return RawResponse(code, text)
    }

    private fun parseStatus(text: String): SessionStatus {
        val json = JSONObject(text)
        val array = json.getJSONArray("receivedChunks")
        val received = buildSet { for (i in 0 until array.length()) add(array.getInt(i)) }
        return SessionStatus(
            sessionId = json.getString("sessionId"),
            receivedChunks = received,
            expectedChunks = json.getInt("expectedChunks"),
            complete = json.getBoolean("complete"),
            nextChunk = if (json.isNull("nextChunk")) null else json.getInt("nextChunk"),
        )
    }

    private fun encode(value: String): String = java.net.URLEncoder.encode(value, "UTF-8")

    companion object {
        const val PROTOCOL_VERSION = 1

        const val HEADER_TOKEN = "authorization"
        const val HEADER_TIMESTAMP = "x-relay-timestamp"
        const val HEADER_SIGNATURE = "x-relay-signature"
        const val HEADER_CONTENT_HASH = "x-relay-content-hash"
        const val HEADER_SEQUENCE = "x-relay-sequence"

        private const val CONNECT_TIMEOUT_MS = 15_000
        private const val READ_TIMEOUT_MS = 120_000

        fun sha256Hex(body: ByteArray): String =
            MessageDigest.getInstance("SHA-256").digest(body).toHex()

        /**
         * `HMAC-SHA256(key, "<version>.<timestamp>.<METHOD>.<path>.<bodyHash>")`.
         *
         * Must match `signBody` in connector/src/protocol.ts exactly — every
         * separator and the uppercase method included.
         */
        fun sign(
            signingKey: String,
            method: String,
            path: String,
            bodyHash: String,
            timestampMs: Long,
        ): String {
            val payload = "$PROTOCOL_VERSION.$timestampMs.${method.uppercase()}.$path.$bodyHash"
            val mac = Mac.getInstance("HmacSHA256")
            mac.init(SecretKeySpec(signingKey.toByteArray(Charsets.UTF_8), "HmacSHA256"))
            return mac.doFinal(payload.toByteArray(Charsets.UTF_8)).toHex()
        }

        private fun ByteArray.toHex(): String =
            joinToString("") { "%02x".format(it) }
    }
}
