import CryptoKit
import Foundation

/// The phone's half of the connector — see `connector/src/protocol.ts`, which is
/// the single source of truth for the wire format.
///
/// Ported from `connector/src/client.ts` method for method. Three
/// implementations have to agree byte for byte on the signature construction, so
/// `ConnectorSigningTests` pins this one against a vector generated by the
/// TypeScript implementation. If that test fails, they have diverged and every
/// request from this platform will be rejected with an error that says nothing
/// about why.
public final class ConnectorClient: @unchecked Sendable {

    public struct Credentials: Sendable, Equatable {
        public let deviceToken: String
        public let signingKey: String

        public init(deviceToken: String, signingKey: String) {
            self.deviceToken = deviceToken
            self.signingKey = signingKey
        }
    }

    public struct SessionManifest: Sendable, Equatable, Codable {
        public let sessionId: String
        public let kind: String
        public let startedAtMs: Int
        public let durationS: Int
        public let totalBytes: Int
        public let chunkBytes: Int
        public let encoding: String
        public let sourceName: String

        public init(
            sessionId: String,
            kind: String = "audio",
            startedAtMs: Int,
            durationS: Int,
            totalBytes: Int,
            chunkBytes: Int = ConnectorClient.chunkBytes,
            encoding: String = "opus",
            sourceName: String
        ) {
            self.sessionId = sessionId
            self.kind = kind
            self.startedAtMs = startedAtMs
            self.durationS = durationS
            self.totalBytes = totalBytes
            self.chunkBytes = chunkBytes
            self.encoding = encoding
            self.sourceName = sourceName
        }
    }

    public struct SessionStatus: Sendable, Equatable, Decodable {
        public let sessionId: String
        public let receivedChunks: [Int]
        public let expectedChunks: Int
        public let complete: Bool
        public let nextChunk: Int?
    }

    public struct UploadProgress: Sendable, Equatable {
        public let sentChunks: Int
        public let totalChunks: Int
        public let sentBytes: Int
        public let totalBytes: Int
        public let skippedChunks: Int
    }

    public struct ConnectorError: Error, Sendable {
        public let status: Int
        public let message: String
    }

    public static let protocolVersion = 1
    public static let chunkBytes = 256 * 1024

    private let baseURL: URL
    private let session: URLSession
    private let now: @Sendable () -> Int
    private let lock = NSLock()
    private var storedCredentials: Credentials?

    public init(
        baseURL: URL,
        credentials: Credentials? = nil,
        session: URLSession = .shared,
        now: @escaping @Sendable () -> Int = { Int(Date().timeIntervalSince1970 * 1000) }
    ) {
        self.baseURL = baseURL
        self.storedCredentials = credentials
        self.session = session
        self.now = now
    }

    public var credentials: Credentials? {
        lock.lock(); defer { lock.unlock() }
        return storedCredentials
    }

    /// Synchronous, so the lock is never held across an `await` — which is a
    /// warning under Swift 5 and an error under Swift 6, for the good reason
    /// that it can park a cooperative-pool thread.
    private func store(_ credentials: Credentials) {
        lock.lock(); defer { lock.unlock() }
        storedCredentials = credentials
    }

    // MARK: - pairing

    @discardableResult
    public func pair(
        deviceId: String,
        deviceName: String,
        pairingCode: String
    ) async throws -> Credentials {
        struct Request: Encodable {
            let deviceId: String
            let platform: String
            let deviceName: String
            let pairingCode: String
        }
        struct Response: Decodable {
            let deviceToken: String
            let signingKey: String
        }

        var request = URLRequest(url: baseURL.appendingPathComponent("v1/pair"))
        request.httpMethod = "POST"
        request.setValue("application/json", forHTTPHeaderField: "content-type")
        request.httpBody = try JSONEncoder().encode(
            Request(
                deviceId: deviceId,
                platform: "ios",
                deviceName: deviceName,
                pairingCode: pairingCode
            )
        )

        let (data, response) = try await session.data(for: request)
        let status = (response as? HTTPURLResponse)?.statusCode ?? 0
        guard status == 200 else {
            throw ConnectorError(status: status, message: String(decoding: data, as: UTF8.self))
        }

        let paired = try JSONDecoder().decode(Response.self, from: data)
        let credentials = Credentials(deviceToken: paired.deviceToken, signingKey: paired.signingKey)
        store(credentials)
        return credentials
    }

    // MARK: - sessions

    @discardableResult
    public func declare(_ manifest: SessionManifest) async throws -> SessionStatus {
        let body = try JSONEncoder().encode(manifest)
        let data = try await send("POST", "/v1/sessions", body: body, contentType: "application/json")
        return try JSONDecoder().decode(SessionStatus.self, from: data)
    }

    public func status(sessionId: String) async throws -> SessionStatus {
        let path = "/v1/sessions/\(escape(sessionId))/status"
        let data = try await send("GET", path, body: Data())
        return try JSONDecoder().decode(SessionStatus.self, from: data)
    }

    @discardableResult
    public func complete(sessionId: String) async throws -> SessionStatus {
        let path = "/v1/sessions/\(escape(sessionId))/complete"
        let data = try await send("POST", path, body: Data())
        return try JSONDecoder().decode(SessionStatus.self, from: data)
    }

    /// Upload a session, sending only what the box does not already have.
    ///
    /// The resume query is unconditional. A phone that uploaded 39 of 40 chunks
    /// before losing signal does not know that it did; asking costs one small
    /// round trip and can save an hour of radio.
    @discardableResult
    public func upload(
        _ manifest: SessionManifest,
        data: Data,
        onProgress: (@Sendable (UploadProgress) -> Void)? = nil
    ) async throws -> SessionStatus {
        let chunkBytes = manifest.chunkBytes
        let totalChunks = data.isEmpty ? 0 : (data.count + chunkBytes - 1) / chunkBytes

        try await declare(manifest)
        let already = Set(try await status(sessionId: manifest.sessionId).receivedChunks)

        var sentChunks = 0
        var sentBytes = 0

        for index in 0 ..< totalChunks {
            let start = index * chunkBytes
            let end = min(start + chunkBytes, data.count)
            let slice = data.subdata(in: start ..< end)

            if already.contains(index) {
                sentBytes += slice.count
                continue
            }

            try await putChunk(sessionId: manifest.sessionId, sequence: index, body: slice)
            sentChunks += 1
            sentBytes += slice.count

            onProgress?(UploadProgress(
                sentChunks: sentChunks,
                totalChunks: totalChunks,
                sentBytes: sentBytes,
                totalBytes: data.count,
                skippedChunks: already.count
            ))
        }

        return try await complete(sessionId: manifest.sessionId)
    }

    private func putChunk(sessionId: String, sequence: Int, body: Data) async throws {
        let path = "/v1/sessions/\(escape(sessionId))/chunks"
        _ = try await send(
            "POST",
            path,
            body: body,
            contentType: "application/octet-stream",
            extraHeaders: [Header.sequence: String(sequence)],
            // 208 means the box already held this chunk, which is success: a
            // client retrying after a lost ACK behaved correctly.
            acceptStatuses: [200, 208]
        )
    }

    // MARK: - plumbing

    @discardableResult
    private func send(
        _ method: String,
        _ path: String,
        body: Data,
        contentType: String? = nil,
        extraHeaders: [String: String] = [:],
        acceptStatuses: Set<Int> = [200]
    ) async throws -> Data {
        guard let credentials else {
            throw ConnectorError(status: 0, message: "not paired")
        }

        let bodyHash = Self.sha256Hex(body)
        let timestamp = now()
        let signature = Self.sign(
            signingKey: credentials.signingKey,
            method: method,
            path: path,
            bodyHash: bodyHash,
            timestampMs: timestamp
        )

        var request = URLRequest(url: baseURL.appendingPathComponent(String(path.dropFirst())))
        request.httpMethod = method
        request.setValue("Bearer \(credentials.deviceToken)", forHTTPHeaderField: Header.token)
        request.setValue(String(timestamp), forHTTPHeaderField: Header.timestamp)
        request.setValue(signature, forHTTPHeaderField: Header.signature)
        request.setValue(bodyHash, forHTTPHeaderField: Header.contentHash)
        contentType.map { request.setValue($0, forHTTPHeaderField: "content-type") }
        for (key, value) in extraHeaders { request.setValue(value, forHTTPHeaderField: key) }
        if method != "GET" { request.httpBody = body }

        let (data, response) = try await session.data(for: request)
        let status = (response as? HTTPURLResponse)?.statusCode ?? 0
        guard acceptStatuses.contains(status) else {
            throw ConnectorError(status: status, message: String(decoding: data, as: UTF8.self))
        }
        return data
    }

    private func escape(_ value: String) -> String {
        value.addingPercentEncoding(withAllowedCharacters: .alphanumerics) ?? value
    }

    // MARK: - signing

    public static func sha256Hex(_ body: Data) -> String {
        SHA256.hash(data: body).map { String(format: "%02x", $0) }.joined()
    }

    /// `HMAC-SHA256(key, "<version>.<timestamp>.<METHOD>.<path>.<bodyHash>")`.
    ///
    /// Must match `signBody` in connector/src/protocol.ts exactly — every
    /// separator and the uppercase method included.
    public static func sign(
        signingKey: String,
        method: String,
        path: String,
        bodyHash: String,
        timestampMs: Int
    ) -> String {
        let payload = "\(protocolVersion).\(timestampMs).\(method.uppercased()).\(path).\(bodyHash)"
        let key = SymmetricKey(data: Data(signingKey.utf8))
        let mac = HMAC<SHA256>.authenticationCode(for: Data(payload.utf8), using: key)
        return mac.map { String(format: "%02x", $0) }.joined()
    }

    public enum Header {
        public static let token = "authorization"
        public static let timestamp = "x-relay-timestamp"
        public static let signature = "x-relay-signature"
        public static let contentHash = "x-relay-content-hash"
        public static let sequence = "x-relay-sequence"
    }
}

public extension ConnectorClient {

    /// Turn a queued record into the resumable upload the box expects.
    ///
    /// The bridge between `Queue.swift` and this client: `StoreAndForwardQueue`
    /// knows about bytes and ids, the connector knows about sessions and chunks,
    /// and this is the only place that has to know both. Hand the result to
    /// `queue.flush(_:)`.
    ///
    /// The record id becomes the session id, which is what makes a replayed sync
    /// idempotent end to end — the queue refuses a delivered id locally, and the
    /// box dedupes on the same string if the queue's memory has rolled over.
    func uploader(
        onProgress: (@Sendable (ConnectorClient.UploadProgress) -> Void)? = nil
    ) -> QueueSend {
        return { [self] record in
            let manifest = SessionManifest(
                sessionId: record.id,
                kind: record.kind,
                startedAtMs: record.meta.startedAtMs ?? record.enqueuedAtMs,
                durationS: record.meta.durationS ?? 0,
                totalBytes: record.body.count,
                encoding: record.meta.encoding ?? "opus",
                sourceName: record.meta.sourceName ?? record.id
            )
            _ = try await upload(manifest, data: record.body, onProgress: onProgress)
        }
    }
}
