import CryptoKit
import Foundation

/// The phone half of `docs/SYSTEM.md` §6.1 — one authenticated WebSocket to
/// `relayd`, JSON envelopes, both directions.
///
/// A port of `glasses/bridge/src/relayd.ts`. Where this and that disagree about
/// the wire, one of them is a bug; `RelaydLinkTests` pins the auth header
/// against a vector generated by the TypeScript, which is the piece that fails
/// silently and unhelpfully when two implementations drift.
///
/// Built for a phone that keeps vanishing. Sleep/wake is the *normal* path, not
/// an error path: reconnect with jittered backoff, put in-flight envelopes back
/// at the **head** of the outbox on an abnormal close, and let the server dedupe
/// on the envelope `id`.
///
/// The frame that ends the redelivery is `ack`, and its shape is not ours to
/// choose: `relayd/internal/api/wire.go` sends `{ re, ok }`, one per accepted
/// frame, and §6.1 documents that. An earlier version of this file — and of the
/// TypeScript — expected a batched `link.ack` carrying `{ ids: [...] }`, which
/// no daemon has ever sent. The daemon and the doc win.

public let linkVersion = 1

/// The subprotocol both ends must agree on. Bump with the envelope version.
public let linkSubprotocol = "relay.v1"

/// How long a link auth header stays valid.
public let authWindowMs = 5 * 60 * 1_000

public let authPrefix = "relay.auth."

// MARK: - vocabulary

/// Phone → server. `docs/SYSTEM.md` §6.1, and nothing beyond it.
public enum PhoneMessage: String, Sendable, Equatable, CaseIterable {
    case utterance
    case touch
    case wear
    case audioChunk = "audio.chunk"
    case photo
    case sessionCommand = "session.command"
    case consentDecision = "consent.decision"
    case syncOffer = "sync.offer"
}

/// Server → phone. `docs/SYSTEM.md` §6.1 — all ten, in the order the doc lists
/// them.
///
/// The first six are the *product* messages. The last four are the ones the
/// transport turned out to need, and each exists because leaving it out made a
/// documented behaviour unimplementable:
///
/// - `ack`: every phone→server frame carries an `id`, and without something that
///   says it landed the store-and-forward queue cannot tell "delivered" from
///   "socket up, daemon dropped it".
/// - `error`: refusals on the same channel, with a code and — for anything
///   unbuilt — the milestone that will build it.
/// - `notify`: `docs/ADAPTERS.md` §7's notification *without* speech. Quiet
///   hours hold the speech and keep the notification.
/// - `confirm.resolved`: retracts a `confirm.request` whose question is gone.
///
/// `glasses/bridge/test/relayd.test.ts` re-parses this enum and pins it against
/// §6.1 and against `relayd/internal/api/wire.go`, because this file cannot be
/// compiled anywhere the rest of the contract is checked.
public enum ServerMessage: String, Sendable, Equatable, CaseIterable {
    case speak
    case uiRender = "ui.render"
    case sessionList = "session.list"
    case confirmRequest = "confirm.request"
    case connectorProposal = "connector.proposal"
    case digest
    case ack
    case error
    case notify
    case confirmResolved = "confirm.resolved"

    /// The six that carry product payloads. The other four are transport frames
    /// the link itself acts on, and reach shaped callbacks instead.
    public var isProduct: Bool {
        switch self {
        case .speak, .uiRender, .sessionList, .confirmRequest, .connectorProposal, .digest:
            return true
        case .ack, .error, .notify, .confirmResolved:
            return false
        }
    }
}

/// The `code` on an `error` frame. Mirrors `relayd/internal/api/wire.go`.
///
/// Deliberately a set of constants rather than an enum: a daemon that grows a
/// new refusal must not become a daemon whose refusals decode to `nil` and
/// vanish. ``ServerErrorFrame/code`` stays a `String`.
public enum ServerErrorCode {
    public static let badEnvelope = "bad_envelope"
    public static let unsupportedVersion = "unsupported_version"
    public static let unknownType = "unknown_type"
    public static let badPayload = "bad_payload"
    /// Named with a milestone. The phone keeps the data rather than deleting it.
    public static let notImplemented = "not_implemented"
    public static let noSuchSession = "no_such_session"
    public static let unsupported = "unsupported"
    public static let failed = "failed"
}

// MARK: - the four transport frames, shaped

/// `Ack` in wire.go: `{ re, ok }`, one per accepted frame.
public struct AckFrame: Sendable, Equatable {
    public let envelope: RelaydEnvelope
    /// The id of the phone→server envelope this acknowledges.
    public let re: String
    public let ok: Bool
    /// True when this ack retired something the link was still holding.
    public let pruned: Bool

    public init(envelope: RelaydEnvelope, re: String, ok: Bool, pruned: Bool) {
        self.envelope = envelope
        self.re = re
        self.ok = ok
        self.pruned = pruned
    }
}

/// `ErrorPayload` in wire.go.
public struct ServerErrorFrame: Sendable, Equatable {
    public let envelope: RelaydEnvelope
    /// The phone→server envelope refused, or nil for an unsolicited error.
    public let re: String?
    public let code: String
    public let message: String
    /// Where the unbuilt half lives, e.g. `"M4 — capture and memory"`.
    public let milestone: String?
    /// True when the refusal retired an envelope the link would have redelivered.
    public let cancelled: Bool

    public init(
        envelope: RelaydEnvelope,
        re: String?,
        code: String,
        message: String,
        milestone: String?,
        cancelled: Bool
    ) {
        self.envelope = envelope
        self.re = re
        self.code = code
        self.message = message
        self.milestone = milestone
        self.cancelled = cancelled
    }
}

/// `Notify` in wire.go.
public struct NotifyFrame: Sendable, Equatable {
    public let envelope: RelaydEnvelope
    public let title: String
    public let body: String
    public let sessions: [String]
    /// Quiet hours: present, soundless. Never a reason to drop it — a held
    /// notification that is also silently discarded is the quiet-hours behaviour
    /// failing with nothing in the log.
    public let silent: Bool
    public let ping: String?

    public init(
        envelope: RelaydEnvelope,
        title: String,
        body: String,
        sessions: [String],
        silent: Bool,
        ping: String?
    ) {
        self.envelope = envelope
        self.title = title
        self.body = body
        self.sessions = sessions
        self.silent = silent
        self.ping = ping
    }
}

/// What the phone should actually put on the lock screen for a `notify`.
///
/// A separate type from ``NotifyFrame`` because this is a *decision* — what to
/// title an untitled notification, whether to make a sound, what collapses with
/// what — and decisions belong in `RelayKit` where `RelayKitTests` can reach
/// them. The app target does nothing but hand these fields to
/// `UNUserNotificationCenter`.
public struct PhoneNotification: Sendable, Equatable {
    public let identifier: String
    public let title: String
    public let body: String
    /// False under quiet hours: present, soundless. Not absent.
    public let playSound: Bool
    /// Groups a session's notifications together in Notification Centre.
    public let threadId: String?

    public init(identifier: String, title: String, body: String, playSound: Bool, threadId: String?) {
        self.identifier = identifier
        self.title = title
        self.body = body
        self.playSound = playSound
        self.threadId = threadId
    }
}

public extension NotifyFrame {

    /// The notification this frame becomes.
    ///
    /// The identifier is the **ping id** where there is one, because relayd
    /// re-pings a waiting question every two minutes with the same id. Keyed by
    /// envelope id instead, ten minutes of waiting would leave five banners
    /// stacked for one question; keyed by ping, each re-ping replaces the last.
    var presentation: PhoneNotification {
        PhoneNotification(
            identifier: ping ?? envelope.id,
            // An empty title would present as a nameless banner. The app's name
            // is a worse title than a real one and a much better title than none.
            title: title.isEmpty ? "Relay" : title,
            body: body,
            playSound: !silent,
            threadId: sessions.first
        )
    }
}

/// `ConfirmResolved` in wire.go.
public struct ConfirmResolvedFrame: Sendable, Equatable {
    public let envelope: RelaydEnvelope
    public let actionId: String
    /// Why: answered in a terminal, turn cancelled, deadline passed.
    public let reason: String
    /// False when this link never saw the question, or already retracted it.
    public let wasOutstanding: Bool

    public init(
        envelope: RelaydEnvelope,
        actionId: String,
        reason: String,
        wasOutstanding: Bool
    ) {
        self.envelope = envelope
        self.actionId = actionId
        self.reason = reason
        self.wasOutstanding = wasOutstanding
    }
}

// MARK: - JSON

/// Just enough JSON to carry a payload through without inventing a schema for
/// it.
///
/// The alternative — decoding every payload into a typed struct at the link
/// layer — makes the link responsible for the product vocabulary, so adding a
/// field on the server becomes a client release. This keeps the link dumb and
/// lets each feature decode what it understands.
public enum JSONValue: Codable, Sendable, Equatable {
    case null
    case bool(Bool)
    case number(Double)
    case string(String)
    case array([JSONValue])
    case object([String: JSONValue])

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if container.decodeNil() {
            self = .null
        } else if let value = try? container.decode(Bool.self) {
            self = .bool(value)
        } else if let value = try? container.decode(Double.self) {
            self = .number(value)
        } else if let value = try? container.decode(String.self) {
            self = .string(value)
        } else if let value = try? container.decode([JSONValue].self) {
            self = .array(value)
        } else if let value = try? container.decode([String: JSONValue].self) {
            self = .object(value)
        } else {
            throw DecodingError.dataCorruptedError(
                in: container,
                debugDescription: "not a JSON value"
            )
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .null: try container.encodeNil()
        case let .bool(value): try container.encode(value)
        case let .number(value): try container.encode(value)
        case let .string(value): try container.encode(value)
        case let .array(value): try container.encode(value)
        case let .object(value): try container.encode(value)
        }
    }

    public subscript(key: String) -> JSONValue? {
        if case let .object(fields) = self { return fields[key] }
        return nil
    }

    public var stringValue: String? {
        if case let .string(value) = self { return value }
        return nil
    }

    public var intValue: Int? {
        if case let .number(value) = self { return Int(value) }
        return nil
    }

    public var boolValue: Bool? {
        if case let .bool(value) = self { return value }
        return nil
    }

    public var arrayValue: [JSONValue]? {
        if case let .array(value) = self { return value }
        return nil
    }

    public static func strings(_ values: [String]) -> JSONValue {
        .array(values.map { .string($0) })
    }
}

// MARK: - envelopes

public struct RelaydEnvelope: Codable, Sendable, Equatable {
    public var v: Int
    public var id: String
    public var type: String
    public var at: Int
    public var payload: JSONValue

    public init(v: Int = linkVersion, id: String, type: String, at: Int, payload: JSONValue = .null) {
        self.v = v
        self.id = id
        self.type = type
        self.at = at
        self.payload = payload
    }
}

public enum LinkErrorCode: String, Sendable, Equatable {
    /// Inbound text was not a valid envelope. Reported, never fatal.
    case malformed
    case versionMismatch
    /// The outbox is full. The caller still owns the data.
    case outboxFull
    /// Sealing was required and no sealer was supplied, or a frame failed to open.
    case sealFailed
    case socketFailed
    case closed
}

public struct LinkError: Error, Sendable, Equatable {
    public let code: LinkErrorCode
    public let message: String

    public init(_ code: LinkErrorCode, _ message: String) {
        self.code = code
        self.message = message
    }
}

public enum Envelopes {

    /// Strict on purpose. An envelope that half-parses produces a UI that acts
    /// on a field it invented, and §6.1 is a contract two languages have to
    /// implement identically.
    public static func parse(_ text: String) throws -> RelaydEnvelope {
        guard let data = text.data(using: .utf8) else {
            throw LinkError(.malformed, "envelope is not UTF-8")
        }
        let raw: JSONValue
        do {
            raw = try JSONDecoder().decode(JSONValue.self, from: data)
        } catch {
            throw LinkError(.malformed, "envelope is not JSON: \(String(describing: error))")
        }
        guard case .object = raw else {
            throw LinkError(.malformed, "envelope must be a JSON object")
        }
        guard let version = raw["v"]?.intValue else {
            throw LinkError(.malformed, "envelope.v must be a number")
        }
        guard version == linkVersion else {
            throw LinkError(
                .versionMismatch,
                "envelope v=\(version), this link speaks v=\(linkVersion)"
            )
        }
        guard let id = raw["id"]?.stringValue, !id.isEmpty else {
            throw LinkError(.malformed, "envelope.id must be a non-empty string")
        }
        guard let type = raw["type"]?.stringValue, !type.isEmpty else {
            throw LinkError(.malformed, "envelope.type must be a non-empty string")
        }
        guard let at = raw["at"]?.intValue else {
            throw LinkError(.malformed, "envelope.at must be a finite number")
        }
        return RelaydEnvelope(id: id, type: type, at: at, payload: raw["payload"] ?? .null)
    }

    public static func serialise(_ envelope: RelaydEnvelope) throws -> String {
        let data = try JSONEncoder().encode(envelope)
        guard let text = String(data: data, encoding: .utf8) else {
            throw LinkError(.malformed, "envelope did not encode as UTF-8")
        }
        return text
    }

    /// RFC 4122 v4 from an injected random source.
    ///
    /// Not `UUID()`: a test that cannot predict the id cannot assert on
    /// redelivery, and the id is the server's dedupe key.
    public static func newId(_ random: RandomSource) -> String {
        var bytes = [UInt8](random(16))
        while bytes.count < 16 { bytes.append(0) }
        bytes[6] = (bytes[6] & 0x0F) | 0x40
        bytes[8] = (bytes[8] & 0x3F) | 0x80
        let hex = Array(bytes.map { String(format: "%02x", $0) }.joined())
        let ranges = [0 ..< 8, 8 ..< 12, 12 ..< 16, 16 ..< 20, 20 ..< 32]
        return ranges.map { String(hex[$0]) }.joined(separator: "-")
    }
}

public typealias RandomSource = @Sendable (Int) -> Data

/// Deterministic bytes for tests: 00 01 02 … wrapping at 256.
public let countingRandom: RandomSource = { count in
    Data((0 ..< max(0, count)).map { UInt8($0 % 256) })
}

public let systemRandom: RandomSource = { count in
    var bytes = [UInt8](repeating: 0, count: max(0, count))
    for index in bytes.indices { bytes[index] = UInt8.random(in: 0 ... 255) }
    return Data(bytes)
}

// MARK: - credentials and auth

public struct DeviceCredential: Sendable, Equatable, Codable {
    public let deviceId: String
    public let boxId: String
    public var boxName: String?
    /// Bearer identity, hex.
    public let deviceToken: String
    /// HMAC key for link auth and body signing, hex.
    public let signingKey: String
    public var protocolVersion: Int
    public var pairedAtMs: Int

    public init(
        deviceId: String,
        boxId: String,
        boxName: String? = nil,
        deviceToken: String,
        signingKey: String,
        protocolVersion: Int = 1,
        pairedAtMs: Int = 0
    ) {
        self.deviceId = deviceId
        self.boxId = boxId
        self.boxName = boxName
        self.deviceToken = deviceToken
        self.signingKey = signingKey
        self.protocolVersion = protocolVersion
        self.pairedAtMs = pairedAtMs
    }
}

public enum LinkAuth {

    /// `relay.auth.<deviceId>.<token>.<timestamp>.<nonce>.<hmac>`, carried as a
    /// WebSocket subprotocol.
    ///
    /// Not in the URL: a bearer token in a query string ends up in proxy logs
    /// and in `URLSession`'s own diagnostics. Everything in it is hex, digits or
    /// percent-encoded, because a subprotocol value is an RFC 7230 token, which
    /// excludes the `/` and `=` that base64 would have brought.
    ///
    /// The signature covers the timestamp and nonce as well as the token, so a
    /// captured header replayed outside its five-minute window fails. The token
    /// alone is never the proof.
    public static func header(
        _ credential: DeviceCredential,
        timestampMs: Int,
        nonce: Data
    ) -> String {
        let nonceHex = hex(nonce)
        let payload = "relay/link/v1\n\(credential.deviceId)\n\(credential.deviceToken)"
            + "\n\(timestampMs)\n\(nonceHex)"
        let key = SymmetricKey(data: bytes(fromHex: credential.signingKey))
        let mac = HMAC<SHA256>.authenticationCode(for: Data(payload.utf8), using: key)
        let fields = [
            percentEncoded(credential.deviceId),
            credential.deviceToken,
            String(timestampMs),
            nonceHex,
            hex(Data(mac)),
        ]
        return authPrefix + fields.joined(separator: ".")
    }

    /// `encodeURIComponent`, spelled out.
    ///
    /// `CharacterSet.urlQueryAllowed` is a *different* set — it permits `&`, `=`
    /// and `+`, all of which would break a dot-separated header. The unreserved
    /// set from RFC 3986 plus JavaScript's four extras is what the TypeScript
    /// produces, so it is what this has to produce.
    static func percentEncoded(_ value: String) -> String {
        let allowed = CharacterSet(charactersIn:
            "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_.!~*'()")
        return value.addingPercentEncoding(withAllowedCharacters: allowed) ?? value
    }

    public static func hex(_ data: Data) -> String {
        data.map { String(format: "%02x", $0) }.joined()
    }

    public static func bytes(fromHex string: String) -> Data {
        var out = Data()
        var index = string.startIndex
        while index < string.endIndex {
            let next = string.index(index, offsetBy: 2, limitedBy: string.endIndex) ?? string.endIndex
            guard next > index, let byte = UInt8(string[index ..< next], radix: 16) else { break }
            out.append(byte)
            index = next
        }
        return out
    }
}

// MARK: - sealing

/// Sealing for the relay route.
///
/// `docs/SYSTEM.md` §7 puts our rendezvous relay between the phone and the box,
/// so "the relay cannot read it" has to be true against *us*. The keys come out
/// of pairing, and pairing needs a PAKE library this platform does not have yet
/// (`docs/APPS-SCOPE.md` §4.3 flags it as a build blocker).
///
/// So this is a seam with no implementation, and ``RelaydLink`` **fails closed**:
/// asked to run sealed with no sealer, it refuses to connect rather than send an
/// utterance in the clear through a server we operate. A missing feature that
/// stops the app is a bug report; a missing feature that silently downgrades
/// privacy is a breach.
public protocol EnvelopeSealer: AnyObject, Sendable {
    func seal(_ text: String) throws -> String
    func open(_ text: String) throws -> String
}

// MARK: - socket seam

public struct RelaydSocketHandlers: Sendable {
    public var onOpen: (@Sendable () -> Void)?
    public var onMessage: (@Sendable (String) -> Void)?
    public var onClose: (@Sendable (Int, String) -> Void)?
    public var onError: (@Sendable (Error) -> Void)?

    public init(
        onOpen: (@Sendable () -> Void)? = nil,
        onMessage: (@Sendable (String) -> Void)? = nil,
        onClose: (@Sendable (Int, String) -> Void)? = nil,
        onError: (@Sendable (Error) -> Void)? = nil
    ) {
        self.onOpen = onOpen
        self.onMessage = onMessage
        self.onClose = onClose
        self.onError = onError
    }
}

/// The subset of WebSocket this link uses.
///
/// Handlers are attached in one call rather than as settable properties, because
/// a protocol with `var onOpen: (() -> Void)? { get set }` cannot also be
/// `Sendable` without lying about it.
public protocol RelaydSocket: AnyObject, Sendable {
    func attach(_ handlers: RelaydSocketHandlers)
    func send(_ text: String)
    func close(code: Int, reason: String)
}

public typealias SocketFactory = @Sendable (URL, [String]) -> RelaydSocket

public enum LinkState: String, Sendable, Equatable {
    case idle
    case connecting
    case open
    /// Waiting out a backoff. Work still queues.
    case reconnecting
    /// Deliberately shut. Only `connect()` reopens it.
    case closed
}

public struct BackoffOptions: Sendable, Equatable {
    public var baseMs: Int
    public var maxMs: Int
    /// Fraction of the interval that is random. 0 = none, 0.5 = half.
    public var jitter: Double

    public init(baseMs: Int = 500, maxMs: Int = 30_000, jitter: Double = 0.5) {
        self.baseMs = baseMs
        self.maxMs = maxMs
        self.jitter = jitter
    }
}

/// Exponential with jitter, `roll` in [0, 1] supplying the randomness.
///
/// The jitter *subtracts* rather than adds, so `maxMs` is a real ceiling. It is
/// not decoration either: every phone in a building loses WiFi at the same
/// moment when an access point reboots, and a fleet that all retries at exactly
/// 1 s, 2 s, 4 s is a self-inflicted thundering herd on the one box.
public func backoffMs(attempt: Int, options: BackoffOptions = BackoffOptions(), roll: Double = 0) -> Int {
    let jitter = min(1, max(0, options.jitter))
    let clampedRoll = min(1, max(0, roll))
    let growth = pow(2.0, Double(max(0, attempt)))
    let exponential = min(Double(options.maxMs), Double(options.baseMs) * growth)
    return Int((exponential * (1 - jitter + jitter * clampedRoll)).rounded())
}

public struct LinkObserver: Sendable {
    public var onStateChanged: (@Sendable (LinkState) -> Void)?
    /// Every inbound envelope, whatever its type.
    public var onMessage: (@Sendable (RelaydEnvelope) -> Void)?
    /// Every envelope §6.1 lists, tagged. The four transport frames also reach
    /// their own shaped callback below; this one exists so a caller can route
    /// the product frames without matching raw strings.
    public var onServerMessage: (@Sendable (ServerMessage, RelaydEnvelope) -> Void)?
    /// A frame landed. Delivered after the outbox has been pruned.
    public var onAck: (@Sendable (AckFrame) -> Void)?
    /// The server refused a frame.
    ///
    /// Named apart from ``onError``, which is *this link's* own faults — a UI
    /// that conflates "the daemon will not do this" with "the socket broke"
    /// retries the first forever.
    public var onServerError: (@Sendable (ServerErrorFrame) -> Void)?
    /// A notification that must reach the phone whether or not anything is
    /// spoken. `docs/ADAPTERS.md` §7.
    public var onNotify: (@Sendable (NotifyFrame) -> Void)?
    /// The question is gone. Take the ping down.
    public var onConfirmResolved: (@Sendable (ConfirmResolvedFrame) -> Void)?
    /// A type this build does not know. Forward compatibility, not an error.
    public var onUnknownType: (@Sendable (RelaydEnvelope) -> Void)?
    /// Bad inbound frame, refused outbox, failed seal. Never thrown at the caller.
    public var onError: (@Sendable (LinkError) -> Void)?
    /// Envelopes put back after an abnormal close, and therefore sent twice.
    public var onRedelivered: (@Sendable ([String]) -> Void)?
    public var onSent: (@Sendable (RelaydEnvelope) -> Void)?

    public init(
        onStateChanged: (@Sendable (LinkState) -> Void)? = nil,
        onMessage: (@Sendable (RelaydEnvelope) -> Void)? = nil,
        onServerMessage: (@Sendable (ServerMessage, RelaydEnvelope) -> Void)? = nil,
        onAck: (@Sendable (AckFrame) -> Void)? = nil,
        onServerError: (@Sendable (ServerErrorFrame) -> Void)? = nil,
        onNotify: (@Sendable (NotifyFrame) -> Void)? = nil,
        onConfirmResolved: (@Sendable (ConfirmResolvedFrame) -> Void)? = nil,
        onUnknownType: (@Sendable (RelaydEnvelope) -> Void)? = nil,
        onError: (@Sendable (LinkError) -> Void)? = nil,
        onRedelivered: (@Sendable ([String]) -> Void)? = nil,
        onSent: (@Sendable (RelaydEnvelope) -> Void)? = nil
    ) {
        self.onStateChanged = onStateChanged
        self.onMessage = onMessage
        self.onServerMessage = onServerMessage
        self.onAck = onAck
        self.onServerError = onServerError
        self.onNotify = onNotify
        self.onConfirmResolved = onConfirmResolved
        self.onUnknownType = onUnknownType
        self.onError = onError
        self.onRedelivered = onRedelivered
        self.onSent = onSent
    }
}

public final class RelaydLink: @unchecked Sendable {

    private struct OutboxEntry {
        let envelope: RelaydEnvelope
        let text: String
    }

    private let url: URL
    private let credential: DeviceCredential
    private let factory: SocketFactory
    private let clock: RelayClock
    private let random: RandomSource
    private let backoff: BackoffOptions
    private let outboxLimit: Int
    private let sealed: Bool
    private let sealer: EnvelopeSealer?
    private var observerBox: LinkObserver

    private let lock = NSLock()
    private var currentState: LinkState = .idle
    private var socket: RelaydSocket?
    private var attempts = 0
    private var retryTask: Task<Void, Never>?
    /// Waiting to go out.
    private var outbox: [OutboxEntry] = []
    /// Handed to a socket, not yet known to have landed.
    private var inFlight: [OutboxEntry] = []
    /// `action_id`s asked and not yet answered or retracted.
    private var confirmations: Set<String> = []

    public init(
        url: URL,
        credential: DeviceCredential,
        socketFactory: @escaping SocketFactory,
        clock: RelayClock = SystemClock(),
        random: @escaping RandomSource = systemRandom,
        backoff: BackoffOptions = BackoffOptions(),
        outboxLimit: Int = 1_000,
        sealed: Bool = false,
        sealer: EnvelopeSealer? = nil,
        observer: LinkObserver = LinkObserver()
    ) {
        self.url = url
        self.credential = credential
        self.factory = socketFactory
        self.clock = clock
        self.random = random
        self.backoff = backoff
        self.outboxLimit = outboxLimit
        self.sealed = sealed
        self.sealer = sealer
        self.observerBox = observer
    }

    /// Replace the observer after construction.
    ///
    /// The app layer cannot pass its closures at init — they capture the object
    /// that owns the link — so this exists rather than a `var` the socket
    /// callbacks would read without a lock.
    public func setObserver(_ observer: LinkObserver) {
        locked { observerBox = observer }
    }

    private var observer: LinkObserver {
        locked { observerBox }
    }

    public var state: LinkState {
        lock.lock(); defer { lock.unlock() }
        return currentState
    }

    /// Envelopes accepted and not yet delivered, including any in flight.
    public var pending: Int {
        lock.lock(); defer { lock.unlock() }
        return outbox.count + inFlight.count
    }

    public var pendingIds: [String] {
        lock.lock(); defer { lock.unlock() }
        return (inFlight + outbox).map(\.envelope.id)
    }

    public var attempt: Int {
        lock.lock(); defer { lock.unlock() }
        return attempts
    }

    /// Questions the box has asked and neither this phone nor the box has closed.
    ///
    /// The list exists so a `confirm.resolved` can retract a specific ping rather
    /// than clearing the screen: waking someone to approve what is already
    /// approved is the failure that frame was added for. Sorted, because a `Set`
    /// has no order and a test that depends on one is a test that flakes.
    public var outstandingConfirmations: [String] {
        lock.lock(); defer { lock.unlock() }
        return confirmations.sorted()
    }

    public func connect() {
        let current = state
        guard current != .connecting, current != .open else { return }
        if sealed && sealer == nil {
            // Fail closed. See ``EnvelopeSealer``.
            setState(.closed)
            observer.onError?(LinkError(
                .sealFailed,
                "relay mode requires a sealer and none was supplied; refusing to send "
                    + "envelopes in the clear through the rendezvous relay"
            ))
            return
        }
        open()
    }

    /// Deliberate shutdown. Anything queued stays queued: the app being closed
    /// is not a reason to throw away an utterance the user already said.
    public func close() {
        let doomed: RelaydSocket? = locked {
            retryTask?.cancel()
            retryTask = nil
            let socket = self.socket
            self.socket = nil
            return socket
        }
        // Even a clean close can lose what is still in the socket's buffer, so
        // in-flight work goes back to the outbox and waits for the next connect.
        requeueInFlight()
        setState(.closed)
        doomed?.close(code: 1000, reason: "client closed")
    }

    /// The OS says the network is back, or the app came to the foreground.
    ///
    /// Collapses the backoff instead of waiting it out. Without this a phone
    /// that wakes into good WiFi sits idle for up to `maxMs` for no reason,
    /// which is the whole sleep/wake case behaving badly.
    public func wake() {
        let current = state
        guard current == .reconnecting || current == .idle else { return }
        locked {
            retryTask?.cancel()
            retryTask = nil
            attempts = 0
        }
        open()
    }

    /// Queue an envelope for delivery. Returns the id, which is also the dedupe
    /// key on the server.
    ///
    /// Never throws for a closed or reconnecting link — that is the normal state
    /// of a phone, and a caller that has to check first is a caller that will
    /// forget.
    @discardableResult
    public func send(_ type: String, _ payload: JSONValue) -> String? {
        let envelope = RelaydEnvelope(
            id: Envelopes.newId(random),
            type: type,
            at: clock.now(),
            payload: payload
        )

        guard let text = try? Envelopes.serialise(envelope) else {
            observer.onError?(LinkError(.malformed, "could not serialise a \(type) envelope"))
            return nil
        }

        // Answering closes the question here, not when the box gets around to
        // saying so. Otherwise a `confirm.resolved` that arrives seconds later
        // reads as a retraction of something still open.
        if type == PhoneMessage.consentDecision.rawValue,
           let actionId = payload["action_id"]?.stringValue {
            locked { _ = confirmations.remove(actionId) }
        }

        let accepted: Bool = locked {
            guard outbox.count + inFlight.count < outboxLimit else { return false }
            outbox.append(OutboxEntry(envelope: envelope, text: text))
            return true
        }

        guard accepted else {
            // Refuse the newest and say so, exactly as `Queue.swift` does.
            // Silently dropping the oldest here would discard the utterance the
            // user is waiting on an answer to.
            observer.onError?(LinkError(
                .outboxFull,
                "link outbox full at \(outboxLimit) envelopes; \"\(type)\" refused"
            ))
            return nil
        }

        flush()
        return envelope.id
    }

    @discardableResult
    public func send(_ type: PhoneMessage, _ payload: JSONValue) -> String? {
        send(type.rawValue, payload)
    }

    // MARK: - internals

    private func open() {
        setState(.connecting)

        let nonce = random(16)
        let header = LinkAuth.header(credential, timestampMs: clock.now(), nonce: nonce)
        let socket = factory(url, [linkSubprotocol, header])
        locked { self.socket = socket }

        socket.attach(RelaydSocketHandlers(
            onOpen: { [weak self, weak socket] in
                guard let self, let socket, self.isCurrent(socket) else { return }
                self.locked { self.attempts = 0 }
                self.setState(.open)
                self.flush()
            },
            onMessage: { [weak self, weak socket] text in
                guard let self, let socket, self.isCurrent(socket) else { return }
                self.receive(text)
            },
            onClose: { [weak self, weak socket] _, _ in
                guard let self, let socket, self.isCurrent(socket) else { return }
                self.locked { self.socket = nil }
                // A clean close still loses whatever was in the socket's buffer,
                // so everything in flight goes back either way.
                self.requeueInFlight()
                if self.state != .closed { self.scheduleRetry() }
            },
            onError: { [weak self, weak socket] error in
                guard let self, let socket, self.isCurrent(socket) else { return }
                self.observer.onError?(
                    LinkError(.socketFailed, String(describing: error))
                )
            }
        ))
    }

    private func isCurrent(_ socket: RelaydSocket) -> Bool {
        lock.lock(); defer { lock.unlock() }
        return self.socket === socket
    }

    private func receive(_ data: String) {
        var text = data
        if let sealer {
            do {
                text = try sealer.open(data)
            } catch {
                observer.onError?(LinkError(
                    .sealFailed,
                    "could not open sealed frame: \(String(describing: error))"
                ))
                return
            }
        }

        let envelope: RelaydEnvelope
        do {
            envelope = try Envelopes.parse(text)
        } catch let error as LinkError {
            observer.onError?(error)
            return
        } catch {
            observer.onError?(LinkError(.malformed, String(describing: error)))
            return
        }

        // Everything documented goes on the firehose first, including the
        // transport frames: a dropped `notify` is the quiet-hours behaviour
        // failing with no log line, which is the bug that made this list ten
        // instead of six.
        observer.onMessage?(envelope)

        guard let type = ServerMessage(rawValue: envelope.type) else {
            observer.onUnknownType?(envelope)
            return
        }
        observer.onServerMessage?(type, envelope)

        switch type {
        case .ack:
            handleAck(envelope)
        case .error:
            handleServerError(envelope)
        case .notify:
            handleNotify(envelope)
        case .confirmResolved:
            handleConfirmResolved(envelope)
        case .confirmRequest:
            // Remembered so the matching `confirm.resolved` can retract it.
            if let actionId = envelope.payload["action_id"]?.stringValue, !actionId.isEmpty {
                locked { _ = confirmations.insert(actionId) }
            }
        case .uiRender:
            // A mini-app's question is remembered exactly like a runtime's, so
            // the matching `confirm.resolved` retracts it. Without this an app
            // that stopped waiting would leave a live-looking button on screen,
            // and the tap would be answered by nothing.
            //
            // The view itself is not decoded here: this type is the transport,
            // and `AppView.parse` is what the surface that draws it calls. A
            // link that understood the vocabulary would be a second place it is
            // defined on this platform.
            if let actionId = envelope.payload["action_id"]?.stringValue, !actionId.isEmpty {
                locked { _ = confirmations.insert(actionId) }
            }
        case .speak, .sessionList, .connectorProposal, .digest:
            break
        }
    }

    /// One ack, one envelope — `{ re, ok }`, exactly `relayd/internal/api/wire.go`.
    ///
    /// An earlier version of this file expected a batched `link.ack` carrying
    /// `{ ids: [...] }`, which no daemon has ever sent, so nothing was ever
    /// pruned and every reconnect redelivered the whole outbox.
    ///
    /// `ok: false` deliberately does *not* prune: it says the frame did not
    /// land, so the entry stays held and goes out again on the next connection.
    private func handleAck(_ envelope: RelaydEnvelope) {
        let re = envelope.payload["re"]?.stringValue ?? ""
        let ok = envelope.payload["ok"]?.boolValue ?? true
        var pruned = false
        if !re.isEmpty, ok {
            pruned = locked { () -> Bool in
                let before = inFlight.count
                inFlight.removeAll { $0.envelope.id == re }
                return inFlight.count != before
            }
        }
        observer.onAck?(AckFrame(envelope: envelope, re: re, ok: ok, pruned: pruned))
    }

    /// A refusal is an answer, so it retires the envelope it names.
    ///
    /// Leaving it in flight would redeliver it on every reconnect for the life
    /// of the queue, and it would be refused every time — `not_implemented` does
    /// not become implemented because a phone asked again. The caller gets the
    /// code and the milestone and decides what to do with the data it still owns.
    private func handleServerError(_ envelope: RelaydEnvelope) {
        let re = envelope.payload["re"]?.stringValue
        let code = envelope.payload["code"]?.stringValue ?? ServerErrorCode.failed
        let message = envelope.payload["message"]?.stringValue ?? ""
        let milestone = envelope.payload["milestone"]?.stringValue

        var cancelled = false
        if let re, !re.isEmpty {
            cancelled = locked { () -> Bool in
                let before = inFlight.count + outbox.count
                inFlight.removeAll { $0.envelope.id == re }
                outbox.removeAll { $0.envelope.id == re }
                return inFlight.count + outbox.count != before
            }
        }

        observer.onServerError?(ServerErrorFrame(
            envelope: envelope,
            re: re,
            code: code,
            message: message,
            milestone: milestone,
            cancelled: cancelled
        ))
    }

    private func handleNotify(_ envelope: RelaydEnvelope) {
        observer.onNotify?(NotifyFrame(
            envelope: envelope,
            title: envelope.payload["title"]?.stringValue ?? "",
            body: envelope.payload["body"]?.stringValue ?? "",
            sessions: envelope.payload["sessions"]?.arrayValue?.compactMap(\.stringValue) ?? [],
            silent: envelope.payload["silent"]?.boolValue ?? false,
            ping: envelope.payload["ping"]?.stringValue
        ))
    }

    private func handleConfirmResolved(_ envelope: RelaydEnvelope) {
        let actionId = envelope.payload["action_id"]?.stringValue ?? ""
        let reason = envelope.payload["reason"]?.stringValue ?? ""
        let wasOutstanding: Bool = locked { () -> Bool in
            guard !actionId.isEmpty else { return false }
            return confirmations.remove(actionId) != nil
        }
        observer.onConfirmResolved?(ConfirmResolvedFrame(
            envelope: envelope,
            actionId: actionId,
            reason: reason,
            wasOutstanding: wasOutstanding
        ))
    }

    private func flush() {
        guard state == .open else { return }

        while true {
            let next: (socket: RelaydSocket, entry: OutboxEntry)? = locked {
                guard let socket, let entry = outbox.first else { return nil }
                return (socket: socket, entry: entry)
            }
            guard let next else { return }
            let socket = next.socket
            let entry = next.entry

            let payload: String
            if let sealer {
                guard let sealedText = try? sealer.seal(entry.text) else {
                    observer.onError?(LinkError(.sealFailed, "could not seal an envelope"))
                    return
                }
                payload = sealedText
            } else {
                payload = entry.text
            }

            socket.send(payload)
            locked {
                if !outbox.isEmpty { outbox.removeFirst() }
                inFlight.append(entry)
            }
            observer.onSent?(entry.envelope)
        }
    }

    /// Put everything unacknowledged back at the **head**, oldest first.
    ///
    /// At the head rather than the tail because `relayd` segments by time and a
    /// reordered utterance lands in the wrong session. Duplicates are the price,
    /// and the envelope `id` is what pays it.
    private func requeueInFlight() {
        let returned: [OutboxEntry] = locked {
            guard !inFlight.isEmpty else { return [] }
            let entries = inFlight
            inFlight = []
            outbox = entries + outbox
            return entries
        }
        guard !returned.isEmpty else { return }
        observer.onRedelivered?(returned.map(\.envelope.id))
    }

    private func scheduleRetry() {
        guard state != .closed else { return }
        setState(.reconnecting)

        let roll = Double(random(1).first ?? 0) / 255
        let delay = backoffMs(attempt: attempt, options: backoff, roll: roll)
        locked {
            attempts += 1
            retryTask?.cancel()
        }

        let task = Task { [weak self] in
            guard let self else { return }
            await self.clock.sleep(ms: delay)
            guard !Task.isCancelled else { return }
            guard self.state == .reconnecting else { return }
            self.open()
        }
        locked { retryTask = task }
    }

    private func setState(_ newState: LinkState) {
        let changed: Bool = locked {
            guard currentState != newState else { return false }
            currentState = newState
            return true
        }
        guard changed else { return }
        observer.onStateChanged?(newState)
    }

    /// Synchronous critical section, for the same reason `MockTransport` has
    /// one: `NSLock.lock()` is unavailable from an async context, and holding a
    /// non-reentrant lock across a suspension point can park a cooperative-pool
    /// thread.
    @inline(__always)
    private func locked<T>(_ body: () -> T) -> T {
        lock.lock()
        defer { lock.unlock() }
        return body()
    }
}

// MARK: - a socket that is not a socket

/// Nothing opens until a test says so.
///
/// Same discipline as ``TestClock`` — no real sockets, no real network.
/// Everything it was told to send is recorded, so a test can assert ordering and
/// redelivery on the exact bytes the relay would have seen.
public final class MockRelaydSocket: RelaydSocket, @unchecked Sendable {

    public let url: URL
    public let protocols: [String]
    private let lock = NSLock()
    private var handlers = RelaydSocketHandlers()
    private var sentText: [String] = []
    private var closedWith: (Int, String)?

    public init(url: URL, protocols: [String]) {
        self.url = url
        self.protocols = protocols
    }

    public var sent: [String] {
        lock.lock(); defer { lock.unlock() }
        return sentText
    }

    public var sentEnvelopes: [RelaydEnvelope] {
        sent.compactMap { try? Envelopes.parse($0) }
    }

    public var isClosed: Bool {
        lock.lock(); defer { lock.unlock() }
        return closedWith != nil
    }

    /// The auth header the link handed to the socket, if any.
    public var authHeader: String? {
        protocols.first { $0.hasPrefix(authPrefix) }
    }

    public func attach(_ handlers: RelaydSocketHandlers) {
        lock.lock()
        self.handlers = handlers
        lock.unlock()
    }

    public func send(_ text: String) {
        lock.lock()
        sentText.append(text)
        lock.unlock()
    }

    public func close(code: Int, reason: String) {
        lock.lock()
        let alreadyClosed = closedWith != nil
        closedWith = (code, reason)
        let handler = handlers.onClose
        lock.unlock()
        guard !alreadyClosed else { return }
        handler?(code, reason)
    }

    // MARK: test controls

    public func simulateOpen() {
        lock.lock(); let handler = handlers.onOpen; lock.unlock()
        handler?()
    }

    public func simulateMessage(_ text: String) {
        lock.lock(); let handler = handlers.onMessage; lock.unlock()
        handler?(text)
    }

    /// An abnormal close — the case the redelivery rule exists for.
    public func simulateDrop(code: Int = 1006, reason: String = "abnormal closure") {
        lock.lock()
        closedWith = (code, reason)
        let handler = handlers.onClose
        lock.unlock()
        handler?(code, reason)
    }

    public func simulateError(_ error: Error) {
        lock.lock(); let handler = handlers.onError; lock.unlock()
        handler?(error)
    }
}

/// Hands out `MockRelaydSocket`s and keeps them, so a test can reach the socket
/// the link is currently using.
public final class MockSocketFactory: @unchecked Sendable {
    private let lock = NSLock()
    private var created: [MockRelaydSocket] = []

    public init() {}

    public var sockets: [MockRelaydSocket] {
        lock.lock(); defer { lock.unlock() }
        return created
    }

    public var latest: MockRelaydSocket? {
        lock.lock(); defer { lock.unlock() }
        return created.last
    }

    public func make() -> SocketFactory {
        return { [self] url, protocols in
            let socket = MockRelaydSocket(url: url, protocols: protocols)
            lock.lock()
            created.append(socket)
            lock.unlock()
            return socket
        }
    }
}
